spring:
  datasource:
    url: jdbc:mysql://localhost:3306/example-app
    username: yves007
    password: hunter)&@&^!007
  lifecycle:
    timeout-per-shutdown-phase: 20s
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect