################## MySQL Configuration ##################
server:
  shutdown: graceful
spring:
  datasource:
    url: jdbc:mysql://[your-host]:[your-port]/[your-database]
    username: your-username
    password: your-password
  lifecycle:
    timeout-per-shutdown-phase: 20s
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect